# Generated by Django 5.0.6 on 2024-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkoutPaymentId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
